/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author deada
 */
public class JFramePrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipalAdmin
     */
    public JFramePrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Salir = new javax.swing.JMenu();
        MenuSalir = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_Inventario = new javax.swing.JCheckBoxMenuItem();
        jMenu_HistorialCompras = new javax.swing.JMenu();
        Menu_Historial = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1230px BG.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -24, 1030, 530));

        jMenu_Salir.setText("Salir");

        MenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        MenuSalir.setSelected(true);
        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenu_Salir.add(MenuSalir);

        jMenuBar1.add(jMenu_Salir);

        jMenu2.setText("Mantenimiento de Usuarios");

        MenuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        MenuUsuarios.setSelected(true);
        MenuUsuarios.setText("Ir al Mantenimiento de Usuarios");
        MenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(MenuUsuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantenimiento de Inventario");

        Menu_Inventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        Menu_Inventario.setSelected(true);
        Menu_Inventario.setText("Ir al Inventario");
        Menu_Inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_InventarioActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Inventario);

        jMenuBar1.add(jMenu3);

        jMenu_HistorialCompras.setText("Historial de Compras");

        Menu_Historial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        Menu_Historial.setSelected(true);
        Menu_Historial.setText("Ir al Historial");
        Menu_Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_HistorialActionPerformed(evt);
            }
        });
        jMenu_HistorialCompras.add(Menu_Historial);

        jMenuBar1.add(jMenu_HistorialCompras);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsuariosActionPerformed
        JFrameUsarios jUsuarios = new JFrameUsarios();
        jUsuarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuUsuariosActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void Menu_InventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_InventarioActionPerformed
        JFrameInventario jInventario = new JFrameInventario();
        jInventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Menu_InventarioActionPerformed

    private void Menu_HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_HistorialActionPerformed
        JFrameHistoricoCompras jhitoricoCompras = new JFrameHistoricoCompras();
        jhitoricoCompras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Menu_HistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem MenuSalir;
    private javax.swing.JCheckBoxMenuItem MenuUsuarios;
    private javax.swing.JCheckBoxMenuItem Menu_Historial;
    private javax.swing.JCheckBoxMenuItem Menu_Inventario;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_HistorialCompras;
    private javax.swing.JMenu jMenu_Salir;
    // End of variables declaration//GEN-END:variables
}
