/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author deada
 */
public class JFramePrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincialCliente
     */
    public JFramePrincipalCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Salir = new javax.swing.JMenu();
        mnu_Salir = new javax.swing.JCheckBoxMenuItem();
        jMenu_Tienda = new javax.swing.JMenu();
        mnu_Tienda = new javax.swing.JCheckBoxMenuItem();
        jMenu_Historico = new javax.swing.JMenu();
        mnuHistorial = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1230px BG.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1030, 530));

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setPreferredSize(new java.awt.Dimension(245, 30));

        jMenu_Salir.setText("Salir");
        jMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_SalirActionPerformed(evt);
            }
        });

        mnu_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        mnu_Salir.setSelected(true);
        mnu_Salir.setText("Salir");
        mnu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_SalirActionPerformed(evt);
            }
        });
        jMenu_Salir.add(mnu_Salir);

        jMenuBar1.add(jMenu_Salir);

        jMenu_Tienda.setText("Ir a la Tienda");
        jMenu_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_TiendaActionPerformed(evt);
            }
        });

        mnu_Tienda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        mnu_Tienda.setSelected(true);
        mnu_Tienda.setText("Ir a la Tienda");
        mnu_Tienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_TiendaActionPerformed(evt);
            }
        });
        jMenu_Tienda.add(mnu_Tienda);

        jMenuBar1.add(jMenu_Tienda);

        jMenu_Historico.setText("Historico de Compras");

        mnuHistorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        mnuHistorial.setSelected(true);
        mnuHistorial.setText("Ir al Historial");
        mnuHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHistorialActionPerformed(evt);
            }
        });
        jMenu_Historico.add(mnuHistorial);

        jMenuBar1.add(jMenu_Historico);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHistorialActionPerformed
        JFrameHistoricoCompras jhitoricoCompras = new JFrameHistoricoCompras();
        jhitoricoCompras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuHistorialActionPerformed

    private void jMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_SalirActionPerformed

    }//GEN-LAST:event_jMenu_SalirActionPerformed

    private void jMenu_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_TiendaActionPerformed

    }//GEN-LAST:event_jMenu_TiendaActionPerformed

    private void mnu_TiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_TiendaActionPerformed
        JFrameTienda jTienda = new JFrameTienda();
        jTienda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnu_TiendaActionPerformed

    private void mnu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_SalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_mnu_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_Historico;
    private javax.swing.JMenu jMenu_Salir;
    private javax.swing.JMenu jMenu_Tienda;
    private javax.swing.JCheckBoxMenuItem mnuHistorial;
    private javax.swing.JCheckBoxMenuItem mnu_Salir;
    private javax.swing.JCheckBoxMenuItem mnu_Tienda;
    // End of variables declaration//GEN-END:variables
}
